

  ========= 测试开始 : 20220325_010814 =========



>>> cases\

[ suite setup ] cases\
suite_setup
打开浏览器
登录管理系统


>>> cases\Admin_action\auto_hytest_action.py

* 检查操作菜单 - UI-0101  -  2022-03-25 01:08:21

  [ case execution steps ]

-- 第 1 步 -- 获取左侧菜单信息 

['客户', '药品', '订单']

-- 第 2 步 -- 检查菜单栏信息 


** 检查点 **  左侧菜单检查 ---->  通过

  PASS 

* 添加客户信息 - UI-0102  -  2022-03-25 01:08:22

  [ case execution steps ]

-- 第 1 步 -- 点击左侧菜单客户按钮 


-- 第 2 步 -- 添加客户信息 


-- 第 3 步 -- 获取添加的客户信息 

['客户名：', '罗湖人民医院', '联系电话：', '0755-120', '地址：', '深圳市罗湖区友谊路人民医院']

** 检查点 **  客户信息检查 ---->  通过

  PASS 


>>> cases\admin_login\auto_hytest_login.py

* 管理员登录 不输入账号 - UI-0001  -  2022-03-25 01:08:25

  [ case execution steps ]
登录管理系统

** 检查点 **  检查提示信息 ---->  通过

  PASS 
  ABORT   (-2147352567, '发生意外。', (0, None, None, None, 0, -2147024809), None) 
Traceback:
  File "c:\python38\lib\site-packages\hytest\utils\signal.py", line 16, in _broadcast
    method(*arg,**kargs)
  File "cases\__st__.py", line 62, in case_result
    self.excel.ActiveWindow.ScrollRow = self.caseNum2Row[caseNo] - 2
  File "c:\python38\lib\site-packages\win32com\client\dynamic.py", line 686, in __setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
pywintypes.com_error: (-2147352567, '发生意外。', (0, None, None, None, 0, -2147024809), None)

